version: '3'
services:
  web:
    image: node:12
    command: bash -c 'yarn install --ignore-optional && yarn dev'
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app