version: "2.4"
services:
  web:
    image: node:12
    command: yarn compose
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    networks:
     - reroll-net

networks: 
  reroll-net:
  