[build]
  command   = "yarn build && yarn copy"
  functions = "app/out_functions"
  publish   = "app/out_publish"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  